services:
  # NOTE(nasr): elastic search runs seperatly and we connect to it from our library
  elasticsearch:
    # NOTE(nasr): changed to a newer version 
    image: 'docker.elastic.co/elasticsearch/elasticsearch:9.3.1'
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      ###########################################
      # TODO(nasr): enable this in the feature  #
      # handles authentication                  #
      ###########################################
      - xpack.security.enabled=false

      # NOTE(nasr): set it to 1G but will this suffice or is this too much?
      - ES_JAVA_OPTS=-Xms1G -Xmx1G
    ports:
      - '9200:9200'
    networks:
      - controlroom-network
  kibana:
    # NOTE(nasr): updated the version
    image: 'docker.elastic.co/kibana/kibana:9.3.1'
    container_name: kibana
    environment:
      - 'ELASTICSEARCH_HOSTS=http://elasticsearch:9200'
    ports:
      - '5601:5601'
    depends_on:
      - elasticsearch
    networks:
      - controlroom-network
networks:
  controlroom-network:
    driver: bridge
