// Code generated by xmlgen. DO NOT EDIT.
// Author: Abdellah El Morabit.
package xml_gen

import (
	"encoding/xml"
	"time"
)

// supressing unused-import errors before goimports is run.
var _ = xml.Name{}
var _ = time.Time{}

type User struct {
	XMLName     xml.Name  `xml:"user" json:"user"`
	Id          string    `xml:"id" json:"id" validate:"required"`
	Type        string    `xml:"type" json:"type" validate:"required"`
	Organisatie string    `xml:"organisatie" json:"organisatie" validate:"required"`
	Datum       time.Time `xml:"datum" json:"datum" validate:"required"`
}
